version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_task_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis_db
    environment:
      REDIS_PASSWORD: password
    command: sh -c 'exec redis-server --requirepass "$REDIS_PASSWORD"'
    ports:
      - "6380:6379"
